version: 2
jobs:
  build:
    docker:
    - image: circleci/ruby:2.4.2-node-browsers
      environment:
        RAILS_ENV: test

    working_directory: ~/repo

    steps:
    - checkout

    - run:
        name: Install Dependencies
        command: bundle install --path vendor/bundle

    - run:
        name: Run Specs
        command: bundle exec rspec --format progress --profile 10 spec

  deploy:
    docker:
    - image: circleci/ruby:2.4.2-node-browsers
      environment:
        RAILS_ENV: test

    working_directory: ~/repo

    environment:
      HEROKU_APP: "pboksz/basia-zawisla"

    steps:
    - checkout

    - run:
        name: Setup Heroku
        command: bash .circleci/setup-heroku.sh

    - run:
        name: Deploy to Heroku
        command: git push heroku master

workflows:
  version: 2
  build_and_deploy:
    jobs:
    - build
    - deploy:
        requires:
          - build
        filters:
          branches:
            only:
              - master
